import 'package:flutter/services.dart';
import 'package:url_launcher/url_launcher.dart';
import '../utils/snackbar_helpers.dart';
import 'launch_service.dart';

/// Free Google Meet integration (launcher + share — no API keys, no
/// WebView).
///
/// Google only accepts MEET-GENERATED codes ("You can only use meet codes
/// generated by meet for you") — a made-up code like `abc-defg-hij` opens
/// an "invalid meeting" page. So the app NEVER invents links: whoever
/// starts the call opens `meet.new` (which yields a real link) and pastes
/// it back into the app, where it is stored on the appointment and shared
/// with the other side (WhatsApp / SMS / copy).
class MeetService {
  MeetService._();

  /// The code portion of a Meet URL, e.g. `abc-defg-hij`.
  ///
  /// Accepts the full URL, `meet.google.com/<code>` without scheme, or the
  /// bare code. Any other input returns `null` — callers treat an invalid
  /// value as "not a meeting link" instead of crashing.
  static String? codeOf(String input) {
    final trimmed = input.trim();
    if (trimmed.isEmpty) return null;
    var candidate = trimmed;

    // Strip scheme + host when a full/partial URL was pasted.
    final withoutScheme = candidate.replaceFirst(RegExp(r'^https?://'), '');
    if (withoutScheme.startsWith('meet.google.com/')) {
      candidate = withoutScheme.substring('meet.google.com/'.length);
    } else if (withoutScheme.contains('meet.google.com/')) {
      final idx = withoutScheme.indexOf('meet.google.com/');
      candidate = withoutScheme.substring(idx + 'meet.google.com/'.length);
    }

    // Drop any trailing path/query cruft.
    candidate = candidate.split(RegExp(r'[/?#]')).first.trim();
    if (candidate.isEmpty) return null;

    // Meet codes are three lowercase groups separated by dashes:
    // `abc-defg-hij` (3–4 chars each). Anything else is not a Meet code.
    if (!RegExp(r'^[a-z0-9]{3,4}(-[a-z0-9]{3,4}){2}$').hasMatch(candidate)) {
      return null;
    }
    return candidate;
  }

  /// Normalizes user input into a full `https://meet.google.com/<code>`
  /// URL, or returns `null` when [input] isn't a valid Meet code/link.
  static String? normalize(String input) {
    final code = codeOf(input);
    return code == null ? null : 'https://meet.google.com/$code';
  }

  /// Opens a meeting in the browser / Meet app. Accepts a full URL or a
  /// bare code; shows an error snackbar when the input isn't a valid Meet
  /// link or the platform can't launch it.
  static Future<void> openMeeting(String urlOrCode) async {
    final url = normalize(urlOrCode);
    if (url == null) {
      showErrorSnackbar('That does not look like a Google Meet link.');
      return;
    }
    final uri = Uri.parse(url);
    try {
      if (await canLaunchUrl(uri)) {
        await launchUrl(uri, mode: LaunchMode.externalApplication);
      } else {
        showErrorSnackbar('Could not open Google Meet.');
      }
    } catch (_) {
      showErrorSnackbar('Could not open Google Meet.');
    }
  }

  /// Opens `meet.new` so the user can start a fresh meeting — Google
  /// generates the real link, which the user then pastes back into the app
  /// via the video-call sheet.
  static Future<void> startNewMeeting() async {
    final uri = Uri.parse('https://meet.new/');
    try {
      if (await canLaunchUrl(uri)) {
        await launchUrl(uri, mode: LaunchMode.externalApplication);
      } else {
        showErrorSnackbar('Could not open Google Meet.');
      }
    } catch (_) {
      showErrorSnackbar('Could not open Google Meet.');
    }
  }

  /// Copies [urlOrCode] (normalized) to the clipboard with feedback.
  static Future<void> copyLink(String urlOrCode) async {
    final url = normalize(urlOrCode);
    if (url == null) {
      showErrorSnackbar('No meeting link to copy.');
      return;
    }
    await Clipboard.setData(ClipboardData(text: url));
    showSuccessSnackbar('Meeting link copied');
  }

  /// Reads the current clipboard text (used to pre-fill the paste-link
  /// dialog). Returns null when empty or unavailable (e.g. web permission
  /// denied).
  static Future<String?> clipboardText() async {
    try {
      final data = await Clipboard.getData(Clipboard.kTextPlain);
      final text = data?.text?.trim() ?? '';
      return text.isEmpty ? null : text;
    } catch (_) {
      return null;
    }
  }

  /// Sends the meeting link to [phone] over WhatsApp with a prefilled
  /// message. Falls back to an error snackbar when there's no link/number.
  static Future<void> shareViaWhatsApp(String? phone, String urlOrCode) async {
    final url = normalize(urlOrCode);
    if (url == null || (phone ?? '').isEmpty) {
      showErrorSnackbar('No meeting link or number to share.');
      return;
    }
    await LaunchService.whatsApp(phone, message: _inviteMessage(url));
  }

  /// Sends the meeting link to [phone] over SMS with a prefilled message.
  static Future<void> shareViaSms(String? phone, String urlOrCode) async {
    final url = normalize(urlOrCode);
    if (url == null || (phone ?? '').isEmpty) {
      showErrorSnackbar('No meeting link or number to share.');
      return;
    }
    await LaunchService.sms(phone, message: _inviteMessage(url));
  }

  /// The prefilled invite text sent with a shared link.
  static String _inviteMessage(String url) =>
      'Join my video consultation on Google Meet: $url';
}
