// Web-only: ensures the connectivity_plus HTML plugin is registered as
// the platform implementation. The autogenerated web_plugin_registrant.dart
// may be tree-shaken in release builds, so we set it explicitly here.
//
// Only compiled when `dart.library.js` is available (web).
//
// The src import is deliberate: DartHtmlConnectivityPlugin is the package's
// canonical web implementation and there is no public equivalent.
// ignore_for_file: implementation_imports

import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart';
import 'package:connectivity_plus/src/web/dart_html_connectivity_plugin.dart';

void ensureWebConnectivityPlatform() {
  ConnectivityPlatform.instance = DartHtmlConnectivityPlugin();
}